### ISSUE TITLE
Network Topology

### ISSUE THREAD

**Issue by Littlehack3r** [wwt9829/CSEC-380-Project#10]
**User Story**
+ Create a network topology using draw.io or the design template of your choosing
+ Include web server, client, load balancer, database, etc.

**DOD**
+ Topology is complete and .png is added to the documentation

**Comment by cnnrshd** [comment]
Network topology has been created and uploaded to documentation folder. 
Thoughts on submission:
- User story asks for load balancer, but given our current storage solution will probably be a single Docker Volume, it doesn't make that much sense to have two web servers hitting this volume. There is also no requirement listed in Project2.0-R2.docx for it.

**Comment by cnnrshd** [comment]
Documentation has been updated in the wiki. Should update the documentation when database services are finalized (What kind of DB we're using)
