### ISSUE TITLE
State-diagrams

### ISSUE THREAD

**Issue by wwt9829** [wwt9829/CSEC-380-Project#13]
**User Story**
- Describe the states that the application can be in
- Describe the actions that can be taken to transition between states

**Definition of Done**
.png(s) added to the Wiki

**Comment by mikelanzafame** [comment]
Use case diagram completed in Draw.io, uploading to Documentation section of wiki.

**Comment by wwt9829** [comment]
Close per above comment

**Comment by wwt9829** [comment]
My bad, this is actually not completed yet

**Comment by mikelanzafame** [comment]
State diagram version 1 complete, uploading now to Documentation.

**Comment by mikelanzafame** [comment]
Branch merged successfully
