### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by wwt9829** [wwt9829/CSEC-380-Project#23]
**User Story**

As a developer I would like to test my application to ensure it is working properly and does not contain security vulnerabilities.

**Definition of Done**

Passing pytest test cases:
- Log in to the application successfully
- Try to log in with the wrong password and fail
- Try to log in with the wrong username and fail

**Comment by mikelanzafame** [comment]
Tests for activity 3 have been written and a committed to a new branch. Testing required now.
