### ISSUE TITLE
Create SSRF Tests

### ISSUE THREAD

**Issue by wwt9829** [wwt9829/CSEC-380-Project#58]
**User Story**

As a user I’d like to be able to demonstrate Server Side Request Forgery. 

**Definition of Done**

A test that demonstrates that the application is vulnerable to SSRF

**Comment by wwt9829** [comment]
There's no assertion here either,

**Comment by mikelanzafame** [comment]
ChaimTube.py currently doesn't like when i pass commands to it, however, after removing the .mp4 file check, code executes further.
