### ISSUE TITLE
Use cases and diagrams

### ISSUE THREAD

**Issue by Littlehack3r** [wwt9829/CSEC-380-Project#9]
**User Story**
+ UML Diagram displaying the functionality of the website
+ Diagram displays each use case of the websites
+ Use case goes over each choice a user can make and the result of that choice
+ Use cases include: login, log out, create user, homepage, etc.
+ Draw.io document in drive 

**DOD**
+ UML Diagram flows through every use case in the website
+ UML Diagram .png is added to the documentation

**Comment by mikelanzafame** [comment]
Use case diagram has been uploaded to the Documentation folder, closing this issue as the task has been completed.
